# Generated by Django 4.2 on 2026-01-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_transactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbalance',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
